src/Web/Areas/Admin/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class ClientsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Web/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class UsersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Web/Controllers/MVC/DefaultController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.Models;

namespace Web.Controllers.MVC
{
    [AllowAnonymous]
	[ApiExplorerSettings(IgnoreApi = true)]
    public class DefaultController : Controller
    {
        private readonly ILogger _logger;

        public DefaultController(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger(GetType());
        }

        public IActionResult Index()
        {
            return View();
        }

		[Route("Privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [Route("Error")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            _logger.LogError("{TraceIdentifier}", HttpContext.TraceIdentifier);
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Route("About")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult About()
        {
            var domain = Assembly.GetAssembly(typeof(Domain.Extensions));
            var infrastructure = Assembly.GetAssembly(typeof(Infrastructure.Extensions));
            var persistence = Assembly.GetAssembly(typeof(Persistence.Extensions));
            var business = Assembly.GetAssembly(typeof(Business.Extensions));
            var web = Assembly.GetAssembly(typeof(Program));

            var models = new List<AboutViewModel>();

            if (domain != null)
                models.Add(new()
                {
                    Name = domain.GetName().Name,
                    Title = domain.GetCustomAttributes(true).OfType<AssemblyTitleAttribute>().FirstOrDefault()?.Title,
                    Description = domain.GetCustomAttributes(true).OfType<AssemblyDescriptionAttribute>().FirstOrDefault()?.Description ?? "Domain Layer",
                    Version = domain.GetName().Version,
                    Published = System.IO.File.GetCreationTime(domain.Location),
                    Color = "#f54437"
                });

            if (infrastructure != null)
                models.Add(new()
                {
                    Name = infrastructure.GetName().Name,
                    Title = infrastructure.GetCustomAttributes(true).OfType<AssemblyTitleAttribute>().FirstOrDefault()?.Title,
                    Description = infrastructure.GetCustomAttributes(true).OfType<AssemblyDescriptionAttribute>().FirstOrDefault()?.Description ?? "Infrastructure Layer",
                    Version = infrastructure.GetName().Version,
                    Published = System.IO.File.GetCreationTime(infrastructure.Location),
                    Color = "#ea1f64"
                });

            if (persistence != null)
                models.Add(new()
                {
                    Name = persistence.GetName().Name,
                    Title = persistence.GetCustomAttributes(true).OfType<AssemblyTitleAttribute>().FirstOrDefault()?.Title,
                    Description = persistence.GetCustomAttributes(true).OfType<AssemblyDescriptionAttribute>().FirstOrDefault()?.Description ?? "Persistence Layer",
                    Version = persistence.GetName().Version,
                    Published = System.IO.File.GetCreationTime(persistence.Location),
                    Color = "#9d28b1",
                });

            if (business != null)
                models.Add(new()
                {
                    Name = business.GetName().Name,
                    Title = business.GetCustomAttributes(true).OfType<AssemblyTitleAttribute>().FirstOrDefault()?.Title,
                    Description = business.GetCustomAttributes(true).OfType<AssemblyDescriptionAttribute>().FirstOrDefault()?.Description ?? "Business Layer",
                    Version = business.GetName().Version,
                    Published = System.IO.File.GetCreationTime(business.Location),
                    Color = "#683bb8",
                });

            if (web != null)
                models.Add(new()
                {
                    Name = web.GetName().Name ?? "Web",
                    Title = web.GetCustomAttributes(true).OfType<AssemblyTitleAttribute>().FirstOrDefault()?.Title,
                    Description = web.GetCustomAttributes(true).OfType<AssemblyDescriptionAttribute>().FirstOrDefault()?.Description ?? "Web Layer",
                    Version = web.GetName().Version,
                    Published = System.IO.File.GetCreationTime(web.Location),
                    Color = "#4052b6",
                });

            var assemblies = this.GetType().Assembly.GetReferencedAssemblies();

            foreach (var item in assemblies)
            {
                var model = new AboutViewModel() { Name = item.Name, Version = item.Version, Dependency = true, };
                if (!models.Any(m => m.Name == model.Name))
                    models.Add(model);
            }

            return View(models);
        }
    }
}

src/Web/Views/Shared/_Empty.cshtml
@inject IConfiguration _configuration
@{
    var twoLetterIsoLanguageName = "en";
    if (Html.UsingLocalization())
    {
        var requestCulture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
        twoLetterIsoLanguageName = requestCulture.RequestCulture.UICulture.TwoLetterISOLanguageName.ToLower();
    }
}

<!doctype html>
<html lang="@twoLetterIsoLanguageName">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@_configuration["AppSettings:Name"] - @ViewData["Title"]</title>

    <partial name="Partials/_FaviconPartial"/>

    <script type="text/javascript">
        /* Sample function that returns boolean in case the browser is Internet Explorer*/
        function isIE() {
          let ua = navigator.userAgent;
          /* MSIE used to detect old browsers and Trident used to newer ones*/
          return ua.indexOf("MSIE ") > -1 || ua.indexOf("Trident/") > -1; 
        }
        /* Create an alert to show if the browser is IE or not */
        if (isIE()){
            window.location = "/browsers.htm";
        }
    </script>

    @await RenderSectionAsync("Header", false)

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <environment include="development">
        @if (@Html.UsingSass())
        {
            <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true"/>
        }
        else
        {
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css"/>
        }
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    </environment>
    <environment exclude="development">
        @if (@Html.UsingSass())
        {
            <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true"/>
        }
        else
        {
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css"/>
        }
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>

    </environment>

    @Html.PageStyles()
    @await RenderSectionAsync("Styles", false)

    <environment include="development">
        @* <style> *@
        @*     * { *@
        @*         border: thin solid red !important; *@
        @*     } *@
        @* </style> *@
    </environment>

</head>
<body id="@(ViewContext.RouteData.Values["area"]?.ToString()?.ToLower())">

    @RenderBody()

    <environment include="development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/popper.js/umd/popper.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/moment.js/moment-with-locales.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/moment.js/moment-with-locales.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @Html.AntiForgeryToken()
    <script>
        let __RequestVerificationToken = $("[name=__RequestVerificationToken]").val();
    </script>

    @Html.PageScripts()
    @await RenderSectionAsync("Scripts", false)

    <partial name="Components/Analytics" />

</body>
</html>

src/Web/Views/Shared/_Footer.cshtml
@inject IConfiguration _configuration
<footer class="d-none d-sm-block mt-5">
    <nav class="navbar navbar-light bg-light fixed-bottom border-top pb-2">
        <div class="container-fluid">
            <span class="navbar-text p-0 m-0">
                &copy; @DateTime.Now.Year - @_configuration["AppSettings:Name"]
            </span>
            <span class="navbar-text p-0 m-0">
                <a data-toggle="tooltip" class="ms-2" title="About" asp-area="" asp-controller="Default" asp-action="About">
                    <i class="fas fa-info-circle"></i>
                </a>
            </span>
        </div>
    </nav>
</footer>

src/Web/Views/Shared/_Header.cshtml
@using Domain.Entities.Identity
@inject SignInManager<User> _signInManager
@inject UserManager<User> _userManager
@inject IConfiguration _configuration

<header class="pb-4">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Default" asp-action="Index">
                <img class="pb-1" src="~/favicon.svg" alt="" width="30" height="30">
                @_configuration["AppSettings:Name"]
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Default" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Default" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Clients" asp-action="Index">Clients</a>
                        </li>
                    }
                    @if (_signInManager.IsSignedIn(User) && Html.UsingSwagger() && _configuration.GetValue<bool>("SwaggerSettings:EnableUI"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="~/api">API</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>

src/Web/Views/Shared/_Layout.cshtml
@{
    Layout = "_Empty";
}

@section Header{
    @await RenderSectionAsync("Header", false)
}

@section Styles{
    @await RenderSectionAsync("Styles", false)
}

<partial name="_Header"/>

<main role="main" id="main-content" class="container p-0">
    @RenderBody()
</main>

<partial name="_Footer"/>

<partial name="Components/Validation"/>

@section Scripts{
    @await RenderSectionAsync("Scripts", false)
}